from setuptools import setup, find_packages

setup(
    name="market-predictor",
    version="1.0.0",
    package_dir={"": "market-predictor"},
    packages=find_packages(where="market-predictor"),
    python_requires=">=3.12",
    install_requires=[
        "pandas>=2.0",
        "numpy>=1.26", 
        "scikit-learn>=1.4",
        "yfinance>=0.2.40",
        "feedparser>=6.0",
        "fastapi>=0.110",
        "uvicorn>=0.29",
        "joblib>=1.3",
        "python-dotenv>=1.0.0",
        "requests>=2.31",
        "beautifulsoup4>=4.12",
        "pypdf>=4.0",
        "pytest>=8.0",
        "httpx>=0.27",
        "pyjwt>=2.8.0",
        "passlib>=1.7.4",
        "argon2-cffi>=23.1.0",
        "redis>=5.0.0",
        "python-multipart>=0.0.6",
        "slowapi>=0.1.9",
        "psutil>=5.9.0",
        "plotly>=7.0.0",
        "mplfinance>=0.12.10b0",
        "matplotlib>=3.11.0",
        "schedule>=1.2.0",
    ],
)