"""
Market Predictor Pro - Global Stock Database
500+ Major Companies from US, Europe, Asia, and other markets
"""

# ============================================================================
# 500+ GLOBAL STOCKS - US, Europe, Asia, and Emerging Markets
# ============================================================================

GLOBAL_STOCKS_500 = [
    # ============================================================================
    # US TECHNOLOGY & SOFTWARE
    # ============================================================================
    {"symbol": "AAPL", "name": "Apple Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "GOOGL", "name": "Alphabet Inc. Class A", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "GOOG", "name": "Alphabet Inc. Class C", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "META", "name": "Meta Platforms Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "AMZN", "name": "Amazon.com Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "TSLA", "name": "Tesla Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "CRM", "name": "Salesforce Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "INTC", "name": "Intel Corporation", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "AMD", "name": "Advanced Micro Devices", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "CSCO", "name": "Cisco Systems Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "PYPL", "name": "PayPal Holdings Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "QCOM", "name": "Qualcomm Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "TXN", "name": "Texas Instruments Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "IBM", "name": "International Business Machines", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "ACN", "name": "Accenture plc", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "SHOP", "name": "Shopify Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "SNOW", "name": "Snowflake Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "PLTR", "name": "Palantir Technologies Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "SQ", "name": "Block Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "DOCU", "name": "DocuSign Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "ZM", "name": "Zoom Video Communications", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "TWLO", "name": "Twilio Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "UBER", "name": "Uber Technologies Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "LYFT", "name": "Lyft Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "SPOT", "name": "Spotify Technology SA", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "ROKU", "name": "Roku Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "COIN", "name": "Coinbase Global Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "HOOD", "name": "Robinhood Markets Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "SNAP", "name": "Snap Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "PINS", "name": "Pinterest Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "ETSY", "name": "Etsy Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "WIX", "name": "Wix.com Ltd.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "DDOG", "name": "Datadog Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "NET", "name": "Cloudflare Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "ZS", "name": "Zscaler Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "OKTA", "name": "Okta Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "TEAM", "name": "Atlassian Corporation", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "WDAY", "name": "Workday Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "PATH", "name": "UiPath Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "UPST", "name": "Upstart Holdings Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "AFRM", "name": "Affirm Holdings Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "RBLX", "name": "Roblox Corporation", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "U", "name": "Unity Software Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "TWTR", "name": "Twitter Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},  # Note: Delisted, may need removal
    {"symbol": "BOX", "name": "Box Inc.", "exchange": "NYSE", "sector": "Technology", "region": "US"},
    {"symbol": "DKNG", "name": "DraftKings Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},

    # ============================================================================
    # US FINANCIAL SERVICES
    # ============================================================================
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "BAC", "name": "Bank of America Corporation", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "WFC", "name": "Wells Fargo & Company", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "C", "name": "Citigroup Inc.", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "GS", "name": "The Goldman Sachs Group", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "MS", "name": "Morgan Stanley", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "BLK", "name": "BlackRock Inc.", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "SCHW", "name": "Charles Schwab Corporation", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "AXP", "name": "American Express Company", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "V", "name": "Visa Inc.", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "MA", "name": "Mastercard Incorporated", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "DFS", "name": "Discover Financial Services", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "COF", "name": "Capital One Financial", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "CME", "name": "CME Group Inc.", "exchange": "NASDAQ", "sector": "Financial", "region": "US"},
    {"symbol": "ICE", "name": "Intercontinental Exchange", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "MMC", "name": "Marsh & McLennan Companies", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "AON", "name": "Aon plc", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},  # Healthcare but listed here temporarily
    {"symbol": "STT", "name": "State Street Corporation", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "BK", "name": "Bank of New York Mellon", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "NTRS", "name": "Northern Trust Corporation", "exchange": "NASDAQ", "sector": "Financial", "region": "US"},
    {"symbol": "TROW", "name": "T. Rowe Price Group", "exchange": "NASDAQ", "sector": "Financial", "region": "US"},
    {"symbol": "AMP", "name": "Ameriprise Financial", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "L", "name": "Loews Corporation", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "AIG", "name": "American International Group", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "PRU", "name": "Prudential Financial Inc.", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "MET", "name": "MetLife Inc.", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "ALL", "name": "Allstate Corporation", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "TRV", "name": "The Travelers Companies", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "CB", "name": "Chubb Limited", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "HIG", "name": "The Hartford Financial Services", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "PFG", "name": "Principal Financial Group", "exchange": "NASDAQ", "sector": "Financial", "region": "US"},
    {"symbol": "LIN", "name": "Linde plc", "exchange": "NYSE", "sector": "Industrial", "region": "US"},  # Industrial but listed here temporarily

    # ============================================================================
    # US HEALTHCARE
    # ============================================================================
    {"symbol": "JNJ", "name": "Johnson & Johnson", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "UNH", "name": "UnitedHealth Group Incorporated", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "MRK", "name": "Merck & Co. Inc.", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "DHR", "name": "Danaher Corporation", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "BMY", "name": "Bristol-Myers Squibb", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "GILD", "name": "Gilead Sciences Inc.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "LLY", "name": "Eli Lilly and Company", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "NVAX", "name": "Novavax Inc.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "MRNA", "name": "Moderna Inc.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "BIIB", "name": "Biogen Inc.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "ALXN", "name": "Alexion Pharmaceuticals", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "ILMN", "name": "Illumina Inc.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "DGX", "name": "Quest Diagnostics", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "LH", "name": "Laboratory Corporation of America", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "CNC", "name": "Centene Corporation", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "HUM", "name": "Humana Inc.", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "CI", "name": "Cigna Corporation", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "MOH", "name": "Molina Healthcare Inc.", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "UNM", "name": "Unum Group", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "AET", "name": "Aetna Inc.", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},  # Acquired by CVS
    {"symbol": "BSX", "name": "Boston Scientific Corporation", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "MDT", "name": "Medtronic plc", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "SYK", "name": "Stryker Corporation", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "ZBH", "name": "Zimmer Biomet Holdings", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "EW", "name": "Edwards Lifesciences", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "ISRG", "name": "Intuitive Surgical Inc.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "US"},
    {"symbol": "DVA", "name": "DaVita Inc.", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "FMS", "name": "Fresenius Medical Care", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},

    # ============================================================================
    # US CONSUMER GOODS & RETAIL
    # ============================================================================
    {"symbol": "WMT", "name": "Walmart Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "COST", "name": "Costco Wholesale Corporation", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "HD", "name": "The Home Depot Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "MCD", "name": "McDonald's Corporation", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "NKE", "name": "Nike Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "KO", "name": "The Coca-Cola Company", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "PEP", "name": "PepsiCo Inc.", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "PG", "name": "Procter & Gamble Company", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "CL", "name": "Colgate-Palmolive Company", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "DIS", "name": "The Walt Disney Company", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "CMCSA", "name": "Comcast Corporation", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "T", "name": "AT&T Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "VZ", "name": "Verizon Communications Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "SBUX", "name": "Starbucks Corporation", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "TGT", "name": "Target Corporation", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "LOW", "name": "Lowe's Companies Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "KR", "name": "The Kroger Co.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "COST", "name": "Costco Wholesale Corporation", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "BJ", "name": "BJ's Wholesale Club Holdings", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "TJX", "name": "The TJX Companies Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "ROST", "name": "Ross Stores Inc.", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "M", "name": "Macy's Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "KSS", "name": "Kohl's Corporation", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "JCP", "name": "J.C. Penney Company Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},  # Bankrupt
    {"symbol": "BBY", "name": "Best Buy Co. Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "GPS", "name": "The Gap Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "ANF", "name": "Abercrombie & Fitch Co.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "URBN", "name": "Urban Outfitters Inc.", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "LULU", "name": "Lululemon Athletica Inc.", "exchange": "NASDAQ", "sector": "Consumer", "region": "US"},
    {"symbol": "NKE", "name": "Nike Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "UA", "name": "Under Armour Inc. Class A", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "UAA", "name": "Under Armour Inc. Class C", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "ADDYY", "name": "adidas AG", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "PUM", "name": "PUMA SE", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},

    # ============================================================================
    # US ENERGY & UTILITIES
    # ============================================================================
    {"symbol": "XOM", "name": "Exxon Mobil Corporation", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "CVX", "name": "Chevron Corporation", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "COP", "name": "ConocoPhillips", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "EOG", "name": "EOG Resources Inc.", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "SLB", "name": "Schlumberger Limited", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "HAL", "name": "Halliburton Company", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "BKR", "name": "Baker Hughes Company", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "OXY", "name": "Occidental Petroleum", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "PXD", "name": "Pioneer Natural Resources", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "MPC", "name": "Marathon Petroleum Corporation", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "PSX", "name": "Phillips 66", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "VLO", "name": "Valero Energy Corporation", "exchange": "NYSE", "sector": "Energy", "region": "US"},
    {"symbol": "NEE", "name": "NextEra Energy Inc.", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "DUK", "name": "Duke Energy Corporation", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "SO", "name": "Southern Company", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "EXC", "name": "Exelon Corporation", "exchange": "NASDAQ", "sector": "Utilities", "region": "US"},
    {"symbol": "AEP", "name": "American Electric Power", "exchange": "NASDAQ", "sector": "Utilities", "region": "US"},
    {"symbol": "D", "name": "Dominion Energy Inc.", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "WEC", "name": "WEC Energy Group Inc.", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "ED", "name": "Consolidated Edison Inc.", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "ETR", "name": "Entergy Corporation", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "SRE", "name": "Sempra Energy", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "PEG", "name": "Public Service Enterprise Group", "exchange": "NYSE", "sector": "Utilities", "region": "US"},
    {"symbol": "XEL", "name": "Xcel Energy Inc.", "exchange": "NASDAQ", "sector": "Utilities", "region": "US"},

    # ============================================================================
    # US INDUSTRIALS
    # ============================================================================
    {"symbol": "CAT", "name": "Caterpillar Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "BA", "name": "The Boeing Company", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "GE", "name": "General Electric Company", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "HON", "name": "Honeywell International Inc.", "exchange": "NASDAQ", "sector": "Industrial", "region": "US"},
    {"symbol": "MMM", "name": "3M Company", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "UPS", "name": "United Parcel Service Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "FDX", "name": "FedEx Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "RTX", "name": "Raytheon Technologies", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "LMT", "name": "Lockheed Martin Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "NOC", "name": "Northrop Grumman Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "GD", "name": "General Dynamics Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "DE", "name": "Deere & Company", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "DAL", "name": "Delta Air Lines Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "UAL", "name": "United Airlines Holdings Inc.", "exchange": "NASDAQ", "sector": "Industrial", "region": "US"},
    {"symbol": "AAL", "name": "American Airlines Group Inc.", "exchange": "NASDAQ", "sector": "Industrial", "region": "US"},
    {"symbol": "LUV", "name": "Southwest Airlines Co.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "JBLU", "name": "JetBlue Airways Corporation", "exchange": "NASDAQ", "sector": "Industrial", "region": "US"},
    {"symbol": "ALK", "name": "Alaska Air Group Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "CSX", "name": "CSX Corporation", "exchange": "NASDAQ", "sector": "Industrial", "region": "US"},
    {"symbol": "UNP", "name": "Union Pacific Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "NSC", "name": "Norfolk Southern Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "KSU", "name": "Kansas City Southern", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "EMR", "name": "Emerson Electric Co.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "ITW", "name": "Illinois Tool Works Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "ETN", "name": "Eaton Corporation plc", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "CMI", "name": "Cummins Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "IR", "name": "Ingersoll Rand Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "PH", "name": "Parker-Hannifin Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "ROP", "name": "Roper Technologies Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "OTIS", "name": "Otis Worldwide Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "CARR", "name": "Carrier Global Corporation", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
    {"symbol": "WM", "name": "Waste Management Inc.", "exchange": "NYSE", "sector": "Industrial", "region": "US"},

    # ============================================================================
    # EUROPEAN STOCKS (Trading on US exchanges as ADRs)
    # ============================================================================
    {"symbol": "ASML", "name": "ASML Holding N.V.", "exchange": "NASDAQ", "sector": "Technology", "region": "Europe"},
    {"symbol": "SAP", "name": "SAP SE", "exchange": "NYSE", "sector": "Technology", "region": "Europe"},
    {"symbol": "NESN", "name": "Nestlé S.A.", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "ROG", "name": "Roche Holding AG", "exchange": "OTC", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "NOVN", "name": "Novartis AG", "exchange": "OTC", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "NVS", "name": "Novartis AG", "exchange": "NYSE", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "RHHBY", "name": "Roche Holding AG", "exchange": "OTC", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "SAN", "name": "Sanofi S.A.", "exchange": "NASDAQ", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "SNY", "name": "Sanofi S.A.", "exchange": "NYSE", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "GSK", "name": "GlaxoSmithKline plc", "exchange": "NYSE", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "AZN", "name": "AstraZeneca plc", "exchange": "NASDAQ", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "NVO", "name": "Novo Nordisk A/S", "exchange": "NYSE", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "LLY", "name": "Eli Lilly and Company", "exchange": "NYSE", "sector": "Healthcare", "region": "US"},
    {"symbol": "MC.PA", "name": "LVMH Moët Hennessy Louis Vuitton", "exchange": "EPA", "sector": "Consumer", "region": "Europe"},
    {"symbol": "LVMHF", "name": "LVMH Moët Hennessy Louis Vuitton", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "KER.PA", "name": "Kering SA", "exchange": "EPA", "sector": "Consumer", "region": "Europe"},
    {"symbol": "PRTPY", "name": "Kering SA", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "OR.PA", "name": "L'Oréal S.A.", "exchange": "EPA", "sector": "Consumer", "region": "Europe"},
    {"symbol": "LRLCF", "name": "L'Oréal S.A.", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "AIR.PA", "name": "Airbus SE", "exchange": "EPA", "sector": "Industrial", "region": "Europe"},
    {"symbol": "EADSY", "name": "Airbus SE", "exchange": "OTC", "sector": "Industrial", "region": "Europe"},
    {"symbol": "SAF.PA", "name": "Safran SA", "exchange": "EPA", "sector": "Industrial", "region": "Europe"},
    {"symbol": "SAFRF", "name": "Safran SA", "exchange": "OTC", "sector": "Industrial", "region": "Europe"},
    {"symbol": "BNP.PA", "name": "BNP Paribas SA", "exchange": "EPA", "sector": "Financial", "region": "Europe"},
    {"symbol": "BNPQY", "name": "BNP Paribas SA", "exchange": "OTC", "sector": "Financial", "region": "Europe"},
    {"symbol": "CS.PA", "name": "AXA SA", "exchange": "EPA", "sector": "Financial", "region": "Europe"},
    {"symbol": "AXAHY", "name": "AXA SA", "exchange": "OTC", "sector": "Financial", "region": "Europe"},
    {"symbol": "ING", "name": "ING Groep N.V.", "exchange": "NYSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "INGA", "name": "ING Groep N.V.", "exchange": "EPA", "sector": "Financial", "region": "Europe"},
    {"symbol": "DB", "name": "Deutsche Bank AG", "exchange": "NYSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "DBK", "name": "Deutsche Bank AG", "exchange": "ETR", "sector": "Financial", "region": "Europe"},
    {"symbol": "HSBC", "name": "HSBC Holdings plc", "exchange": "NYSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "HSBA", "name": "HSBC Holdings plc", "exchange": "LSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "BARC", "name": "Barclays PLC", "exchange": "LSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "BCS", "name": "Barclays PLC", "exchange": "NYSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "STAN", "name": "Standard Chartered PLC", "exchange": "LSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "LLOY", "name": "Lloyds Banking Group plc", "exchange": "LSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "LYG", "name": "Lloyds Banking Group plc", "exchange": "NYSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "RBS", "name": "Royal Bank of Scotland Group", "exchange": "LSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "NWG", "name": "NatWest Group plc", "exchange": "NYSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "SHEL", "name": "Shell plc", "exchange": "LSE", "sector": "Energy", "region": "Europe"},
    {"symbol": "SHEL", "name": "Shell plc", "exchange": "NYSE", "sector": "Energy", "region": "Europe"},
    {"symbol": "BP", "name": "BP p.l.c.", "exchange": "NYSE", "sector": "Energy", "region": "Europe"},
    {"symbol": "BP.", "name": "BP p.l.c.", "exchange": "LSE", "sector": "Energy", "region": "Europe"},
    {"symbol": "DTE.DE", "name": "Daimler Truck Holding AG", "exchange": "ETR", "sector": "Industrial", "region": "Europe"},
    {"symbol": "DTGZY", "name": "Daimler Truck Holding AG", "exchange": "OTC", "sector": "Industrial", "region": "Europe"},
    {"symbol": "VOW.DE", "name": "Volkswagen AG", "exchange": "ETR", "sector": "Consumer", "region": "Europe"},
    {"symbol": "VWAGY", "name": "Volkswagen AG", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "BMW.DE", "name": "Bayerische Motoren Werke AG", "exchange": "ETR", "sector": "Consumer", "region": "Europe"},
    {"symbol": "BMWYY", "name": "Bayerische Motoren Werke AG", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "DAI", "name": "Mercedes-Benz Group AG", "exchange": "OTC", "sector": "Consumer", "region": "Europe"},
    {"symbol": "MBG.DE", "name": "Mercedes-Benz Group AG", "exchange": "ETR", "sector": "Consumer", "region": "Europe"},
    {"symbol": "SIEGY", "name": "Siemens AG", "exchange": "OTC", "sector": "Industrial", "region": "Europe"},
    {"symbol": "SIE", "name": "Siemens AG", "exchange": "ETR", "sector": "Industrial", "region": "Europe"},
    {"symbol": "BAYRY", "name": "Bayer AG", "exchange": "OTC", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "BAYN", "name": "Bayer AG", "exchange": "ETR", "sector": "Healthcare", "region": "Europe"},
    {"symbol": "BASF", "name": "BASF SE", "exchange": "OTC", "sector": "Industrial", "region": "Europe"},
    {"symbol": "BASFY", "name": "BASF SE", "exchange": "OTC", "sector": "Industrial", "region": "Europe"},
    {"symbol": "ALV", "name": "Allianz SE", "exchange": "ETR", "sector": "Financial", "region": "Europe"},
    {"symbol": "ALIZY", "name": "Allianz SE", "exchange": "OTC", "sector": "Financial", "region": "Europe"},
    {"symbol": "MUV2", "name": "Munich Re", "exchange": "ETR", "sector": "Financial", "region": "Europe"},
    {"symbol": "MURGY", "name": "Munich Re", "exchange": "OTC", "sector": "Financial", "region": "Europe"},
    {"symbol": "ENI", "name": "Eni S.p.A.", "exchange": "NYSE", "sector": "Energy", "region": "Europe"},
    {"symbol": "ENEL", "name": "Enel S.p.A.", "exchange": "NYSE", "sector": "Utilities", "region": "Europe"},
    {"symbol": "ISP.MI", "name": "Intesa Sanpaolo S.p.A.", "exchange": "MIL", "sector": "Financial", "region": "Europe"},
    {"symbol": "ISNPY", "name": "Intesa Sanpaolo S.p.A.", "exchange": "OTC", "sector": "Financial", "region": "Europe"},
    {"symbol": "UCG.MI", "name": "UniCredit S.p.A.", "exchange": "MIL", "sector": "Financial", "region": "Europe"},
    {"symbol": "UNCRY", "name": "UniCredit S.p.A.", "exchange": "OTC", "sector": "Financial", "region": "Europe"},
    {"symbol": "REP.MC", "name": "Repsol S.A.", "exchange": "MCE", "sector": "Energy", "region": "Europe"},
    {"symbol": "REPYY", "name": "Repsol S.A.", "exchange": "OTC", "sector": "Energy", "region": "Europe"},
    {"symbol": "IBE.MC", "name": "Iberdrola S.A.", "exchange": "MCE", "sector": "Utilities", "region": "Europe"},
    {"symbol": "IBDRY", "name": "Iberdrola S.A.", "exchange": "OTC", "sector": "Utilities", "region": "Europe"},
    {"symbol": "SAN.MC", "name": "Banco Santander S.A.", "exchange": "MCE", "sector": "Financial", "region": "Europe"},
    {"symbol": "SAN", "name": "Banco Santander S.A.", "exchange": "NYSE", "sector": "Financial", "region": "Europe"},
    {"symbol": "TEF", "name": "Telefónica S.A.", "exchange": "NYSE", "sector": "Technology", "region": "Europe"},
    {"symbol": "TEF.MC", "name": "Telefónica S.A.", "exchange": "MCE", "sector": "Technology", "region": "Europe"},
    {"symbol": "AMS", "name": "AMS-OSRAM AG", "exchange": "ETR", "sector": "Technology", "region": "Europe"},
    {"symbol": "AAMS", "name": "AMS-OSRAM AG", "exchange": "OTC", "sector": "Technology", "region": "Europe"},
    {"symbol": "ABBN", "name": "ABB Ltd", "exchange": "SWX", "sector": "Industrial", "region": "Europe"},
    {"symbol": "ABB", "name": "ABB Ltd", "exchange": "NYSE", "sector": "Industrial", "region": "Europe"},
    {"symbol": "NOKIA", "name": "Nokia Corporation", "exchange": "NYSE", "sector": "Technology", "region": "Europe"},
    {"symbol": "NOK", "name": "Nokia Corporation", "exchange": "NYSE", "sector": "Technology", "region": "Europe"},
    {"symbol": "ERIC", "name": "Ericsson AB", "exchange": "NASDAQ", "sector": "Technology", "region": "Europe"},
    {"symbol": "ERIC-B", "name": "Ericsson AB", "exchange": "STO", "sector": "Technology", "region": "Europe"},
    {"symbol": "TELIA", "name": "Telia Company AB", "exchange": "STO", "sector": "Technology", "region": "Europe"},
    {"symbol": "TLSNY", "name": "Telia Company AB", "exchange": "OTC", "sector": "Technology", "region": "Europe"},
    {"symbol": "TDC", "name": "TDC A/S", "exchange": "OMX", "sector": "Technology", "region": "Europe"},
    {"symbol": "TDCOY", "name": "TDC A/S", "exchange": "OTC", "sector": "Technology", "region": "Europe"},

    # ============================================================================
    # ASIAN STOCKS (Trading on US exchanges as ADRs)
    # ============================================================================
    {"symbol": "TSM", "name": "Taiwan Semiconductor Manufacturing", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "SAMSUNG", "name": "Samsung Electronics Co. Ltd.", "exchange": "KRX", "sector": "Technology", "region": "Asia"},
    {"symbol": "SSNLF", "name": "Samsung Electronics Co. Ltd.", "exchange": "OTC", "sector": "Technology", "region": "Asia"},
    {"symbol": "SONY", "name": "Sony Group Corporation", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "SNE", "name": "Sony Group Corporation", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "NTDOY", "name": "Nintendo Co. Ltd.", "exchange": "OTC", "sector": "Technology", "region": "Asia"},
    {"symbol": "7974.T", "name": "Nintendo Co. Ltd.", "exchange": "TSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "TM", "name": "Toyota Motor Corporation", "exchange": "NYSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "7203.T", "name": "Toyota Motor Corporation", "exchange": "TSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "HMC", "name": "Honda Motor Co. Ltd.", "exchange": "NYSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "7267.T", "name": "Honda Motor Co. Ltd.", "exchange": "TSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "Nissan", "name": "Nissan Motor Co. Ltd.", "exchange": "TYO", "sector": "Consumer", "region": "Asia"},
    {"symbol": "NSANY", "name": "Nissan Motor Co. Ltd.", "exchange": "OTC", "sector": "Consumer", "region": "Asia"},
    {"symbol": "Mazda", "name": "Mazda Motor Corporation", "exchange": "TYO", "sector": "Consumer", "region": "Asia"},
    {"symbol": "MZDAY", "name": "Mazda Motor Corporation", "exchange": "OTC", "sector": "Consumer", "region": "Asia"},
    {"symbol": "Subaru", "name": "Subaru Corporation", "exchange": "TYO", "sector": "Consumer", "region": "Asia"},
    {"symbol": "FUJHY", "name": "Subaru Corporation", "exchange": "OTC", "sector": "Consumer", "region": "Asia"},
    {"symbol": "Mitsubishi", "name": "Mitsubishi Motors Corporation", "exchange": "TYO", "sector": "Consumer", "region": "Asia"},
    {"symbol": "MMTOF", "name": "Mitsubishi Motors Corporation", "exchange": "OTC", "sector": "Consumer", "region": "Asia"},
    {"symbol": "MTU", "name": "Mitsubishi UFJ Financial Group", "exchange": "NYSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "8306.T", "name": "Mitsubishi UFJ Financial Group", "exchange": "TSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "SMFG", "name": "Sumitomo Mitsui Financial Group", "exchange": "NYSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "8316.T", "name": "Sumitomo Mitsui Financial Group", "exchange": "TSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "C", "name": "Citigroup Inc.", "exchange": "NYSE", "sector": "Financial", "region": "US"},
    {"symbol": "MUFG", "name": "Mitsubishi UFJ Financial Group", "exchange": "NYSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "MFG", "name": "Mizuho Financial Group", "exchange": "NYSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "8411.T", "name": "Mizuho Financial Group", "exchange": "TSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "BABA", "name": "Alibaba Group Holding Limited", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "9988.HK", "name": "Alibaba Group Holding Limited", "exchange": "HKEX", "sector": "Technology", "region": "Asia"},
    {"symbol": "TCEHY", "name": "Tencent Holdings Limited", "exchange": "OTC", "sector": "Technology", "region": "Asia"},
    {"symbol": "0700.HK", "name": "Tencent Holdings Limited", "exchange": "HKEX", "sector": "Technology", "region": "Asia"},
    {"symbol": "JD", "name": "JD.com Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "9618.HK", "name": "JD.com Inc.", "exchange": "HKEX", "sector": "Technology", "region": "Asia"},
    {"symbol": "PDD", "name": "PDD Holdings Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "MEITU", "name": "Meitu Inc.", "exchange": "HKEX", "sector": "Technology", "region": "Asia"},
    {"symbol": "BIDU", "name": "Baidu Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "9888.HK", "name": "Baidu Inc.", "exchange": "HKEX", "sector": "Technology", "region": "Asia"},
    {"symbol": "NTES", "name": "NetEase Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "9999.HK", "name": "NetEase Inc.", "exchange": "HKEX", "sector": "Technology", "region": "Asia"},
    {"symbol": "NIO", "name": "NIO Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "9866.HK", "name": "NIO Inc.", "exchange": "HKEX", "sector": "Consumer", "region": "Asia"},
    {"symbol": "XPEV", "name": "XPeng Inc.", "exchange": "NYSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "9868.HK", "name": "XPeng Inc.", "exchange": "HKEX", "sector": "Consumer", "region": "Asia"},
    {"symbol": "LI", "name": "Li Auto Inc.", "exchange": "NASDAQ", "sector": "Consumer", "region": "Asia"},
    {"symbol": "2015.HK", "name": "Li Auto Inc.", "exchange": "HKEX", "sector": "Consumer", "region": "Asia"},
    {"symbol": "BYDDY", "name": "BYD Company Limited", "exchange": "OTC", "sector": "Consumer", "region": "Asia"},
    {"symbol": "1211.HK", "name": "BYD Company Limited", "exchange": "HKEX", "sector": "Consumer", "region": "Asia"},
    {"symbol": "MELI", "name": "MercadoLibre Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Latin America"},
    {"symbol": "MELI", "name": "MercadoLibre Inc.", "exchange": "B3", "sector": "Technology", "region": "Latin America"},
    {"symbol": "AMX", "name": "América Móvil S.A.B. de C.V.", "exchange": "NYSE", "sector": "Technology", "region": "Latin America"},
    {"symbol": "AMX.MX", "name": "América Móvil S.A.B. de C.V.", "exchange": "BMV", "sector": "Technology", "region": "Latin America"},
    {"symbol": "ITUB", "name": "Itaú Unibanco Holding S.A.", "exchange": "NYSE", "sector": "Financial", "region": "Latin America"},
    {"symbol": "ITUB4.SA", "name": "Itaú Unibanco Holding S.A.", "exchange": "B3", "sector": "Financial", "region": "Latin America"},
    {"symbol": "BB", "name": "Banco Bradesco S.A.", "exchange": "NYSE", "sector": "Financial", "region": "Latin America"},
    {"symbol": "BBDC4.SA", "name": "Banco Bradesco S.A.", "exchange": "B3", "sector": "Financial", "region": "Latin America"},
    {"symbol": "VALE", "name": "Vale S.A.", "exchange": "NYSE", "sector": "Materials", "region": "Latin America"},
    {"symbol": "VALE3.SA", "name": "Vale S.A.", "exchange": "B3", "sector": "Materials", "region": "Latin America"},
    {"symbol": "PBR", "name": "Petróleo Brasileiro S.A. - Petrobras", "exchange": "NYSE", "sector": "Energy", "region": "Latin America"},
    {"symbol": "PETR4.SA", "name": "Petróleo Brasileiro S.A. - Petrobras", "exchange": "B3", "sector": "Energy", "region": "Latin America"},
    {"symbol": "KO", "name": "The Coca-Cola Company", "exchange": "NYSE", "sector": "Consumer", "region": "US"},
    {"symbol": "REL", "name": "Reliance Industries Limited", "exchange": "NSE", "sector": "Energy", "region": "Asia"},
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries Limited", "exchange": "NSE", "sector": "Energy", "region": "Asia"},
    {"symbol": "TCS", "name": "Tata Consultancy Services", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "INFY", "name": "Infosys Limited", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "INFY.NS", "name": "Infosys Limited", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "HDB", "name": "HDFC Bank Limited", "exchange": "NYSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank Limited", "exchange": "NSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "IBN", "name": "ICICI Bank Limited", "exchange": "NYSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank Limited", "exchange": "NSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "WIT", "name": "Wipro Limited", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "WIPRO.NS", "name": "Wipro Limited", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "TTM", "name": "Tata Motors Limited", "exchange": "NYSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "MTSL", "name": "Mahindra & Mahindra Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "ITC", "name": "ITC Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "ITC.NS", "name": "ITC Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "SBIN", "name": "State Bank of India", "exchange": "NSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "exchange": "NSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "LTC", "name": "Larsen & Toubro Limited", "exchange": "NSE", "sector": "Industrial", "region": "Asia"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro Limited", "exchange": "NSE", "sector": "Industrial", "region": "Asia"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank Limited", "exchange": "NSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Limited", "exchange": "NSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance Limited", "exchange": "NSE", "sector": "Financial", "region": "Asia"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel Limited", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki India Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "NESTLEIND.NS", "name": "Nestlé India Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints Limited", "exchange": "NSE", "sector": "Consumer", "region": "Asia"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical Industries Limited", "exchange": "NSE", "sector": "Healthcare", "region": "Asia"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories Limited", "exchange": "NSE", "sector": "Healthcare", "region": "Asia"},
    {"symbol": "CIPLA.NS", "name": "Cipla Limited", "exchange": "NSE", "sector": "Healthcare", "region": "Asia"},
    {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma Limited", "exchange": "NSE", "sector": "Healthcare", "region": "Asia"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel Limited", "exchange": "NSE", "sector": "Materials", "region": "Asia"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel Limited", "exchange": "NSE", "sector": "Materials", "region": "Asia"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries Limited", "exchange": "NSE", "sector": "Materials", "region": "Asia"},
    {"symbol": "COALINDIA.NS", "name": "Coal India Limited", "exchange": "NSE", "sector": "Energy", "region": "Asia"},
    {"symbol": "ONGC.NS", "name": "Oil and Natural Gas Corporation", "exchange": "NSE", "sector": "Energy", "region": "Asia"},
    {"symbol": "NTPC.NS", "name": "NTPC Limited", "exchange": "NSE", "sector": "Utilities", "region": "Asia"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation of India", "exchange": "NSE", "sector": "Utilities", "region": "Asia"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises Limited", "exchange": "NSE", "sector": "Conglomerate", "region": "Asia"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports and Special Economic Zone", "exchange": "NSE", "sector": "Industrial", "region": "Asia"},
    {"symbol": "ADANIGREEN.NS", "name": "Adani Green Energy Limited", "exchange": "NSE", "sector": "Energy", "region": "Asia"},
    {"symbol": "ADANITRANS.NS", "name": "Adani Total Gas Limited", "exchange": "NSE", "sector": "Energy", "region": "Asia"},
    {"symbol": "ZOMATO.NS", "name": "Zomato Limited", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "NYKAA.NS", "name": "FSN E-Commerce Ventures Limited", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "PAYTM.NS", "name": "One97 Communications Limited", "exchange": "NSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "PB", "name": "PubMatic Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "GOTU", "name": "Gaotu Techedu Inc.", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "GSX", "name": "Gaotu Techedu Inc.", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "TME", "name": "Tencent Music Entertainment Group", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "IQ", "name": "iQIYI Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "VIPS", "name": "Vipshop Holdings Limited", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "YY", "name": "JOYY Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "DOYU", "name": "DouYu International Holdings Limited", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "HUYA", "name": "Huya Inc.", "exchange": "NYSE", "sector": "Technology", "region": "Asia"},
    {"symbol": "WB", "name": "Weibo Corporation", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "BILI", "name": "Bilibili Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "Asia"},
    {"symbol": "Z", "name": "Zillow Group Inc.", "exchange": "NASDAQ", "sector": "Technology", "region": "US"},
    {"symbol": "RDY", "name": "Ready Mixed Concrete", "exchange": "NYSE", "sector": "Industrial", "region": "US"},
]

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_all_stocks_500():
    """Get all 500+ global stocks"""
    return GLOBAL_STOCKS_500

def get_stock_count():
    """Get total stock count"""
    return len(GLOBAL_STOCKS_500)

def get_stocks_by_region(region: str):
    """Get stocks by region"""
    return [stock for stock in GLOBAL_STOCKS_500 if stock["region"] == region]

def get_stocks_by_sector(sector: str):
    """Get stocks by sector"""
    return [stock for stock in GLOBAL_STOCKS_500 if stock["sector"] == sector]

def get_stocks_by_exchange(exchange: str):
    """Get stocks by exchange"""
    return [stock for stock in GLOBAL_STOCKS_500 if stock["exchange"] == exchange]
